In [15]:
import numpy as np
from sklearn.linear_model import LinearRegression
from scipy import stats

    Задача 1

Подберите два признака (из четырёх) так, чтобы уровень линейной зависимости целевой
переменной от значений этих признаков был максимальным. Другими словами, модель линейной
регрессии на этих признаках должна давать наилучший результат. В качестве ответа
запишите значение коэффициента детерминации для модели на этих признаках.

In [13]:
x = np.array([[ 1.22401313,  2.30868478,  3.03636353,  2.69287214],
               [-0.18757272,  1.30337355,  5.12093014,  3.46363202],
               [-0.81094525,  1.82463398,  5.79686488,  1.86159445],
               [ 0.75129018,  2.67392052,  3.65529809,  1.66746094],
               [ 0.00972362,  1.97367255,  2.50594319,  1.69755173],
               [-0.62972637,  0.77750764,  2.84124027,  4.54410559],
               [ 2.29536229,  1.81206697,  1.95026215,  1.51874636],
               [ 0.0920418 ,  2.26971361,  7.47708735,  2.61081203],
               [ 2.39252799,  3.17563985,  3.61420599,  5.10773362],
               [ 0.54983815,  2.87988651,  1.65752765,  1.59635987]])
y = np.array([ 9.26193358,  9.700363  ,  8.67214805,  8.74796974,  6.18689108,
               7.53312713,  7.57643777, 12.44965478, 14.29010746,  6.68361218 ])

In [9]:
x.shape

(10, 4)

In [5]:
XTX = x.T.dot(x)
XTX

array([[ 14.45578256,  16.18970672,  13.75963817,  16.36899923],
       [ 16.18970672,  48.82147094,  77.94638231,  54.96579726],
       [ 13.75963817,  77.94638231, 172.28091363, 103.55453384],
       [ 16.36899923,  54.96579726, 103.55453384,  86.78508203]])

In [7]:
XTX_inv = np.linalg.inv(XTX)

b = XTX_inv.dot(x.T).dot(y)

b

array([1., 1., 1., 1.])

In [14]:
lr = LinearRegression(fit_intercept=False).fit(x, y)
lr.coef_

array([1., 1., 1., 1.])

Задача 2

Является ли значимым уравнение регрессии, полученное в предыдущей задаче? В качестве
ответа запишите 1, если является, и 0 иначе.

In [ ]:
1

Задача 3

Для проведения A/B-тестирования сайта интернет-магазина были получены следующие данные: страница `A` была посещена 2509 раз, из них 77 закончились совершением покупки, страница `B` была посещена 1465 раз, 60 из них закончились совершением покупки. Является ли значимым отличие конверсии на страницах `A` и `B`? В качестве ответа запишите 1, если является, и 0 иначе.

_Подсказка_. Реализуйте двухвыборочный t-тест. В качестве выборок здесь можно взять наборы меток совершения покупки (0 или 1) каждым посетителем.

In [24]:
x1 = np.concatenate((np.zeros(2509 - 77), np.ones(77)))
x2 = np.concatenate((np.zeros(1465 - 60), np.ones(60)))

In [25]:
stats.ttest_ind(x1, x2, equal_var=False)

Ttest_indResult(statistic=-1.6504551408398205, pvalue=0.09896479217925898)

Значение статистики не попало в критическую область. Гипотеза о равенстве математических
ожиданий не отвергается.

In [ ]:
0