In [1]:
# Задание 1
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]], dtype=np.int8)
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]], dtype=int8)

In [3]:
mean_a = np.mean(a, axis=1)
mean_a

array([2. , 8.4])

In [4]:
# Задание 2
a_centered = a - mean_a.reshape(-1,  1)
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [5]:
# Задание 3
a_centered_sp = (a_centered * a_centered).sum(axis=0)
a_centered_sp

array([6.76, 0.16, 7.76, 3.56, 2.96])

In [6]:
a_centered_sp / (a[0].size - 1)

array([1.69, 0.04, 1.94, 0.89, 0.74])