In [10]:
import numpy as np
import pandas as pd

In [52]:
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [53]:
boston = load_boston()

In [54]:
feature_names = boston["feature_names"]

feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [55]:
target = boston["target"]

target[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

In [56]:
X = pd.DataFrame(data, columns=feature_names)

X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [57]:
y = pd.DataFrame(target, columns=["price"])

y.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [59]:
lr = LinearRegression()

In [60]:
lr.fit(X_train, y_train)

LinearRegression()

In [61]:
y_pred = lr.predict(X_test)
y_pred[:10]

array([[28.64896005],
       [36.49501384],
       [15.4111932 ],
       [25.40321303],
       [18.85527988],
       [23.14668944],
       [17.3921241 ],
       [14.07859899],
       [23.03692679],
       [20.59943345]])

In [62]:
check_test = pd.DataFrame({
    "y_test": y_test["price"],
    "y_pred": y_pred.flatten(),
})

check_test.head(10)

y_test     y_pred
173    23.6  28.648960
274    32.4  36.495014
491    13.6  15.411193
72     22.8  25.403213
452    16.1  18.855280
76     20.0  23.146689
316    17.8  17.392124
140    14.0  14.078599
471    19.6  23.036927
500    16.8  20.599433

In [66]:
R2 = r2_score(check_test["y_pred"], check_test["y_test"])
R2

0.6693702691495628

In [88]:
# Задание 2

from sklearn.ensemble import RandomForestRegressor

In [89]:
clf = RandomForestRegressor(
    n_estimators=1000,
    max_depth=12
)

In [92]:
results = clf.fit(X_train, y_train.values[:, 0])
results

RandomForestRegressor(max_depth=12, n_estimators=1000)

In [97]:
y_tree_pred = clf.predict(X_test)
y_tree_pred[:10]

array([22.67958338, 31.32824667, 16.42396228, 23.90320916, 17.18284106,
       21.70086869, 19.78322528, 14.85182705, 21.31147488, 20.95670775])

In [98]:
check_tree_test = pd.DataFrame({
    "y_test": y_test["price"],
    "y_pred": y_tree_pred.flatten(),
})

check_tree_test.head(10)

y_test     y_pred
173    23.6  22.679583
274    32.4  31.328247
491    13.6  16.423962
72     22.8  23.903209
452    16.1  17.182841
76     20.0  21.700869
316    17.8  19.783225
140    14.0  14.851827
471    19.6  21.311475
500    16.8  20.956708

In [99]:
R2_tree = r2_score(check_tree_test["y_pred"], check_tree_test["y_test"])
R2_tree

0.8439893137201391

In [ ]:
# RandomForestRegressor более успешно предсказывает цену недвижимости. Чем ближе r2 к 1 тем лучше.